# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

#ifdef OPLUS_FEATURE_DNS_HOOK
#ShiQianhua@NETWORK.DATA.1816043, 2021/08/09, add for dns hook.
obj-$(CONFIG_OPLUS_FEATURE_DNS_HOOK) += oplus_dns_hook/
#endif /* OPLUS_FEATURE_DNS_HOOK */

#ifdef OPLUS_FEATURE_STATS_CALC
#ShiQianhua@NETWORK.DATA.2360276, 2021/11/02 add for kernel stats
obj-$(CONFIG_OPLUS_FEATURE_STATS_CALC) += oplus_stats_calc/
#endif /* OPLUS_FEATURE_STATS_CALC */

#ifdef OPLUS_FEATURE_QR_SCAN
#yangzhaoji@NETWORK.DATA.2534809, 2022/01/19, Add for qr scan scene
obj-$(CONFIG_OPLUS_FEATURE_QR_SCAN) += oplus_qr_scan/
#endif /* OPLUS_FEATURE_QR_SCAN */
